Importar NumPy:

In [2]:
import numpy as np

Crear arrays a partir de listas:

In [3]:
x1=np.array([1,2.1,3,4.2,5])
x2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1)
print(x2)

[1.  2.1 3.  4.2 5. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Funciones de NumPy para crear arrays:

In [4]:
x1=np.zeros(5,dtype=float)
x2=np.ones((2,2,2),dtype=int)
x3=np.full((2,4),2.78)
x4=np.random.random((2,2))
print(x1)
print(x2)
print(x3)
print(x4)

[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[2.78 2.78 2.78 2.78]
 [2.78 2.78 2.78 2.78]]
[[0.83283583 0.00970198]
 [0.522996   0.27388839]]
